// src/data/courseContent.js
const courseContent = {
  PostGraduation1: {
    title: "Post Graduation 1 ",
    description: "HTML (HyperText Markup Language) structures web content.",
    topics: ["Tags", "Forms", "Tables", "Semantic HTML"],
    image: "/images/html.png",
    paymentLink: "https://rzp.io/l/html-course",
    brochure: "/brochures/html.pdf",
    link: "/courses/PostGraduation1",
  },
  PostGraduation2: {
    title: "Post Graduation 2 ",
    description: "CSS (Cascading Style Sheets) styles web content.",
    topics: ["Selectors", "Box Model", "Flexbox", "Grid"],
    image: "/images/css.png",
    paymentLink: "https://rzp.io/l/css-course",
    brochure: "/brochures/css.pdf",
    link: "/courses/PostGraduation2",
  },
  AppliedDataScience: {
    title: "Applied Data Science",
    description: "React is a JavaScript library for building user interfaces.",
    topics: ["JSX", "Components", "Hooks", "State Management"],
    image: "/images/react.png",
    paymentLink: "https://rzp.io/l/react-course",
    brochure: "/brochures/react.pdf",
    link: "/courses/AppliedDataScience",
  },
  AdvancedMachineLearning: {
    title: "Advanced Machine Learning",
    description: "Node.js is a JavaScript runtime for server-side programming.",
    topics: ["Event Loop", "File System", "Modules", "NPM"],
    image: "/images/nodejs.png",
    paymentLink: "https://rzp.io/l/node-course",
    brochure: "/brochures/nodejs.pdf",
    link: "/courses/AdvancedMachineLearning",
  },
  AdvancedAI: {
    title: "Advanced Artificial Intelligence",
    description: "Express is a Node.js framework for building APIs.",
    topics: ["Routing", "Middleware", "Error Handling", "API creation"],
    image: "/images/express.png",
    paymentLink: "https://rzp.io/l/express-course",
    brochure: "/brochures/express.pdf",
    link: "/courses/AdvancedAI",
  },
  AppliedScience: {
    title: "Applied Science",
    description: "MongoDB is a NoSQL database used for modern web apps.",
    topics: ["Documents", "CRUD", "Aggregation", "Indexes"],
    image: "/images/mongodb.png",
    paymentLink: "https://rzp.io/l/mongodb-course",
    brochure: "/brochures/mongodb.pdf",
    link: "/courses/AdvancedScience",
  },
  CareerAcceleration: {
    title: "Career Acceleration",
    description: "Docker is used to containerize applications.",
    topics: ["Images", "Containers", "Volumes", "Docker Compose"],
    image: "/images/docker.png",
    paymentLink: "https://rzp.io/l/docker-course",
    brochure: "/brochures/docker.pdf",
    link: "/courses/CareerAcceleration",
  },
  MachineLearning: {
    title: "Machine Learning",
    description: "Kubernetes is an orchestration tool for containerized apps.",
    topics: ["Pods", "Deployments", "Services", "Volumes"],
    image: "/images/kubernetes.png",
    paymentLink: "https://rzp.io/l/kubernetes-course",
    brochure: "/brochures/kubernetes.pdf",
    link: "/courses/MachineLearning",
  },
  DataAnalytic: {
    title: "Data Analytics",
    description: "Kubernetes is an orchestration tool for containerized apps.",
    topics: ["Pods", "Deployments", "Services", "Volumes"],
    image: "/images/kubernetes.png",
    paymentLink: "https://rzp.io/l/kubernetes-course",
    brochure: "/brochures/kubernetes.pdf",
    link: "/courses/DataAnalytic",
  },
};

export default courseContent;
